name: GitHub-Profile-3D-Contrib

on:
  # Executa automaticamente todo dia às 6h da manhã UTC
  schedule:
    - cron: '0 6 * * *'
  # Permite execução manual
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate 3D contribution graph
        uses: yoshi389111/github-profile-3d-contrib@latest

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions[bot]@users.noreply.github.com
          git add -A
          git commit -m "Generate 3D Contribution Graph" || echo "No changes to commit"
          git push
